### ISSUE TITLE
How to send data in a triggered event

### ISSUE THREAD

**Issue by decapo01** [jducoeur/jquery-facade#19]
How would I send data from a triggered event to the event listener.

for example

```
$(dom.document).trigger("my-event", ???data-goes-here???)

$(dom.document).on("my-event", (e: JQueryEventObject)=>{
  
})

**Comment by jducoeur** [comment]
Answered on StackOverflow.

**Comment by decapo01** [comment]
Here is a link to the answer in case someone comes to this page.

[http://stackoverflow.com/questions/42664261/scala-js-jquery-facade-send-data-through-trigger-and-on/42672450](http://stackoverflow.com/questions/42664261/scala-js-jquery-facade-send-data-through-trigger-and-on/42672450)

I'm using the untyped facade at the moment and it worked. It was the pattern matching that I was missing. I assume it works the same with this library.

Please don't take this the wrong way but shouldn't simple stuff like this be examples in the read me?  I understand it's a wrapper over jquery and in this instance I'm just mimicking something else I did in JQuery with javscript but it's not obvious from the read me how to do theste things with scalajs.  It's the same with the other JQuery library.  It's kind of the same with the Play Framework and all other things scala as well.

Thanks again for the helpful answer and the library.

**Comment by jducoeur** [comment]
Problem is, it's just too large a project for me to undertake.  As it was, getting the jquery-facade written properly took several work days; documenting it to even a decent first approximation would probably take at least a week, and I simply don't have that time.

So I depend on [the Scala.js documentation](https://www.scala-js.org/doc/) (which any SJS developer should read thoroughly) for the details on how to think about the JS/SJS relationship, and the [jQuery documentation](http://api.jquery.com/) for the details about how the functions themselves work.  This library can't cover all the ins and outs of using Scala and Scala.js -- it's a vast topic.

But as always, pull requests are welcomed, for documentation at least as much as the API itself.  More contributors would help with this...

**Comment by decapo01** [comment]
I have another question.  If you want me to open a new issue I will.  If I try to send multiple items over the trigger method I cannot find a way to get more than the first one in the on method.

For Example

```
$(dom.document).trigger("my-event", 100, 200)
```

in the on method the 200 is always undefined.  Do you know why this is?


If I try an array
```
$(dom.document).trigger("my-event", Array(100, 200))
```
and try to match on the array I get ```Uncaught $c_s_MatchError```

if I just try to print the array without matching It only prints the 100

I've also tried to make a class to use

```
class MyRange(val min: Int, val max: Int) extends js.Any
```

but this throws an error in javascript when trying to match MyRange in the on method

```
Uncaught TypeError: jsx$3 is not a constructor
```

I've also tried to make a ```@ScalaJSDefined``` trait and companion object but I then get a compile error in the match statement

**Comment by jducoeur** [comment]
I don't have any clear answers -- like I said, I haven't used `trigger()` with data parameters myself.  This is mainly a jQuery question, and my own jQuery expertise only goes so far.

The `MatchError` is interesting.  I do wonder if you're getting into trouble with `Array` somehow.  Using the explicit `class` instead is the way I'd probably do it.  Is there a reason why you're making it `extends js.Any`?  That is usually *not* appropriate unless you want to use that data structure from raw JavaScript; my instinct would be to just use an ordinary Scala class.  (Indeed, I'd probably use a routine case class for this.)

**Comment by decapo01** [comment]
With your library the case class works in the trigger method.  With the org.scalajs.jquery library I get a compile error when trying to send a case class over the trigger method

```
type mismatch
required: scala.scalajs.js.Any
```
that's why I created a class MyRange that extends js.Any.  I switched back to your library in the middle of this.  I may raise an issue in the org.scalajs.jquery project.  Thanks again for the help

**Comment by jducoeur** [comment]
Ah, I see.  Yeah, this sort of signature problem is common with the scalajs-jquery library.  Keep in mind that that's a relatively quick-and-dirty library, written in the earliest days of the Scala.js project, and it has *scads* of problems when trying to use it seriously.  That's why I wrote jquery-facade as a ground-up rewrite: I found it frustrating to use scalajs-jquery for a real project.

I've proposed deprecating scalajs-jquery entirely, and have gotten agreement in principle from its maintainers; I think they'd be happy to be done with it.  I just need to find some time to rewrite the examples on the Scala.js website to use jquery-facade instead, and then we'll probably move forward with that.  So I don't recommend worrying about it too much -- just use jquery-facade, which is much more carefully designed, especially when it comes to the types...

**Comment by decapo01** [comment]
Not to bombard you with messages in the issues section but I've put my money where my mouth is and started a wiki for this project.  I'm using this library on a small project that I have in order to get a better understanding of scalajs.  I will be including example how-tos on the wiki page in case anybody else runs accross this library and wants to use it.

**Comment by jducoeur** [comment]
Okay, sounds good.  Once you have a reasonable amount of content, if it looks likely to be useful drop me a line -- we might link to that from the README.

(BTW, if you want to take this out of Issues here, I'm frequently on Gitter...)
