### ISSUE TITLE
ScalaJS 1.0.0-M3

### ISSUE THREAD

**Issue by randm-ch** [jducoeur/jquery-facade#24]
Hi there

Could you publish an artifact for ScalaJS 1.0.0-M3 or are you awaiting the stable release?

Cheers!
Raphael

**Comment by jducoeur** [comment]
Hmm -- good point, since the milestone has been active for a rather long time.  I'll look into it: thanks for pointing it out...

**Comment by er1c** [comment]
scalajs M7 is now out with scala 2.13-M5 which is going to (has become?) the RC1, might be a good time to get that ready/make sure there aren't any issues

**Comment by tflucke** [comment]
Maybe I'm just too new with using maven, but it seems to me like there's still no published artifact compiled with ScalaJS 1.0.0.  Is that correct?

**Comment by frne** [comment]
I was able to build it for sjs `1.0` locally. Could provide a PR, but a `jducoeur/jsext` release for sjs `1.0` is needed.

See jducoeur/jsext#19.
