### ISSUE TITLE
Scala-2.13 Support

### ISSUE THREAD

**Issue by abrighton** [jducoeur/jquery-facade#29]
Any plans to make a new release for Scala-2.13?

**Comment by jducoeur** [comment]
Yeah -- the problem is just that I changed machines since I last cut a release, and I have to figure out how to get things properly set up to do so in my new environment.  It just needs me to be able to scrounge a couple of hours to get all the kinks worked out there...

**Comment by mikla** [comment]
@jducoeur I see that everything is ready to be published for Scala 2.13 and Scala.js 1.0.0.
I appreciate if you can find time to do so :)
Thank you!

**Comment by jducoeur** [comment]
Long since done, but just realized that I never thought to close the issue.
