### ISSUE TITLE
"org.querki" %%% "jquery-facade" % "2.0" can't be found

### ISSUE THREAD

**Issue by lancewalton** [jducoeur/jquery-facade#33]
I have this in my build.sbt:

`
lazy val client = project
  .settings(
    libraryDependencies ++= Seq(
      "org.querki"                    %%% "jquery-facade"             % "2.0"
    )
  ).dependsOn(shared)
`

When I start sbt, I get this:

`
(client / update) sbt.librarymanagement.ResolveException: Error downloading org.querki:jquery-facade_2.13:2.0
Not found
Not found
not found: /Users/lance/.ivy2/local/org.querki/jquery-facade_2.13/2.0/ivys/ivy.xml
not found: https://repo1.maven.org/maven2/org/querki/jquery-facade_2.13/2.0/jquery-facade_2.13-2.0.pom
(client / ssExtractDependencies) sbt.librarymanagement.ResolveException: Error downloading org.querki:jquery-facade_2.13:2.0
Not found
Not found
not found: /Users/lance/.ivy2/local/org.querki/jquery-facade_2.13/2.0/ivys/ivy.xml
not found: https://repo1.maven.org/maven2/org/querki/jquery-facade_2.13/2.0/jquery-facade_2.13-2.0.pom
Total time: 1 s, completed 23 Oct 2020, 20:18:32
`

**Comment by jducoeur** [comment]
Hmm.  I'm not up to 2.13 myself yet (sadly), but I thought this was right.

Which version of Scala.js are you on?  Looking at Maven, I think that this is only published for Scala 2.13 with Scala.js 1.x, not 0.6 -- might that be the problem?

**Comment by lancewalton** [comment]
Hi.

I'm using this:

`addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.3.0")`

**Comment by lancewalton** [comment]
Looking at https://repo1.maven.org/maven2/org/querki/ , there's no jquery-facade_2.13 directory.

**Comment by jducoeur** [comment]
Well, sure -- there wouldn't be.  Since it's a Scala.js library, the artifact name is different.  It's at https://repo1.maven.org/maven2/org/querki/jquery-facade_sjs1_2.13/ instead.  Don't know why that's not being picked up by sbt, though...

**Comment by lancewalton** [comment]
Ah, I see.

I've been doing this in IntelliJ. I've just tried it from the command line & it succeeded, so it's obviously something wrong with my IntelliJ configuration.

Apologies.

**Comment by jducoeur** [comment]
No prob -- common problem.  In general, I consider IntelliJ to be a very unreliable indicator.  (To the point where I always have a Terminal tab open, with plain old sbt running in it, and do all my actual build/run/debug in that.)  Glad it got resolved.

**Comment by lancewalton** [comment]
Yes. I do the terminal thing too. Just neglected to try it. Doh!
