### ISSUE TITLE
Update to scalajs-dom v2.0.0

### ISSUE THREAD

**Issue by pweisenburger** [jducoeur/jquery-facade#34]
Would it be possible to publish jquery-facade for scalajs-dom v2.0.0? As stated in the [release notes](https://github.com/scala-js/scala-js-dom/releases/tag/v2.0.0), the 2.x series is not binary-compatible with the 1.x series. So, for projects that use v2.0.0 and jquery-facade, the latter needs to be built against v2.0.0.

It seems, simply updating the dependency suffices:

```diff
  libraryDependencies ++= Seq(
    "org.querki" %%% "querki-jsext" % "0.10",
-   "org.scala-js" %%% "scalajs-dom" % "0.9.8"
+   "org.scala-js" %%% "scalajs-dom" % "2.0.0"
  )
```

**Comment by jducoeur** [comment]
Fixed as of version 2.1, thanks to @tflucke.
