### ISSUE TITLE
Scala 3 Support

### ISSUE THREAD

**Issue by matomer** [jducoeur/jquery-facade#36]
Hi, 

First of all I'd like to say thank you for a great and useful library.
Scala 3 seems to be quite mature and it would be very nice to have scala 3 support in this library. 
I see that there's already a pull request to implement scala 3 support.
I know you probably have very little time and much more important things to do, so I'd like to know if there are any plans to merge it in the future?

**Comment by SimLej18** [comment]
Hi,

Can confirm that, as a newcomer to Scala and Scala.js, having to go through all the versioning stuff (incompatibility with scalajs-dom 2.0.0 and scala 3) just for a basic JQuery facade is quite rough. I would really appreciate if someone took the time to consider merging the recent pull request. In my humble opinion, it would instantly benefit jquery-facade in making it not seem like deprecated code.

**Comment by jducoeur** [comment]
Yeah, sorry.  The problem is entirely that I haven't done a library release in ages, so I have to remind myself how to do it.  (I'm also not in a position to test it myself, so I have to take the PR on trust.)  But I'll try to deal with this soon -- apologies for the delays...

**Comment by jducoeur** [comment]
Okay, done -- sorry for the long delay.

(At this point, the library is ripe for someone motivated to fork it and take it over -- my head's not currently in the game here.)

**Comment by SimLej18** [comment]
Thank you very much !
