### ISSUE TITLE
after method fails to insert element

### ISSUE THREAD

**Issue by kineticz** [jducoeur/jquery-facade#5]
Here is the code:

```
$("ul li").after((elem: dom.Element, idx: Int) => ("index: " + idx: ElementDesc))
```

If I break down the call as:

```
    val tf: js.ThisFunction1[dom.Element, Int, ElementDesc] = (e: dom.Element, i: Int) => {
      println("adding index...")
      ("index: " + i): ElementDesc
    }
    val ulli = $("ul li")
    println(ulli)
    println(tf)
    ulli.after(tf)
```

Then I can see "adding index..." printed in the console, but the elements were not added.

**Comment by jducoeur** [comment]
This code:

```
dl.after({(elem:dom.Element, index:Int) => println(s"The index is $index"); tbl:ElementDesc})
```

works correctly for me, so I'm _pretty_ sure the facade is correct.  You're probably hitting some other jQuery problem, but I don't have any good guesses as to what it is, I'm afraid...

**Comment by kineticz** [comment]
But if I use jquery directly in javascript:

```
        $("ul li").after(function(i) {return "index" + i })
```

Everything works. Is it possible that scala.js made a mistake somewhere?

**Comment by kineticz** [comment]
Yeah, the facade looks fine to me, conforms to the js equivalent.

**Comment by jducoeur** [comment]
Sounds likely to be _some_ kind of timing problem, but I don't have any clever guesses as to exactly what, I'm afraid...

**Comment by jducoeur** [comment]
Actually -- hmm.  This really is a very weird error.  Since you're getting the "adding index..." message, that suggests that .after() is being called successfully, which means that it's not the usual sort of inability to find the rendered DOM nodes.  What happens if you do the direct version:

```
$("ul li").after("<p>hello</p>")
```

Also, I wasn't clear from the Gitter conversation -- was append() behaving any differently from after()?

**Comment by kineticz** [comment]
That works fine.

**Comment by kineticz** [comment]
append behaves exactly the same.

**Comment by jducoeur** [comment]
I confess, I'm a bit stumped.  My own experiments suggest that

```
$("ul li").after("<p>hello</p>")
```

and

```
$("ul li").after({(elem:dom.Element, index:Int) => "<p>hello</p>":ElementDesc})
```

should be equivalent.  If they aren't, I'm kind of at a loss.  Conceivably, it could be a jQuery bug -- you might try, instead of returning a string, returning an actual DOM node (which is what I'm doing in my case).

**Comment by kineticz** [comment]
Could you try `$("ul li").after({(elem:dom.Element, index:Int) => "<p>hello</p>":ElementDesc})
` on your machine?

**Comment by kineticz** [comment]
I mean that exact line. 

Also, what version of jquery do you use?

**Comment by kineticz** [comment]
I don't think it's jquery's problem, though. The jquery code works perfectly in the browser, as I have shown.

**Comment by kineticz** [comment]
I have tried 2.1.4 and 1.11.3, results are the same.

**Comment by jducoeur** [comment]
Trying the exact line is difficult -- I'm doing my testing in the context of Querki, which is a gigantic code base, and doesn't have any easy way to fit that in.  The nearest easy equivalent I can do is:

```
dl.after({(elem:dom.Element, index:Int) => "<p>hello</p>":ElementDesc})
```

and that works fine.

As for the jQuery version, I'm getting that from jquery-facade.  Aren't you?

**Comment by jducoeur** [comment]
Wait, I'm confused -- trying it how?  What do your build.sbt and HTML files look like?  You shouldn't be specifying jQuery manually -- doing so can cause all sorts of unpredictable havoc.

**Comment by kineticz** [comment]
Well, is it possible to setup a toy project for this?

I am using the js file directly, but that shouldn't matter, right?

**Comment by kineticz** [comment]
Ah, I will upload it to github.

**Comment by kineticz** [comment]
There you go: https://github.com/kindlychung/sjs-dp

**Comment by kineticz** [comment]
And if I don't manually specify jquery, I get this:

```

bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery(anonymous function) @ bootstrap.min.js:6
bootstrap-datepicker.min.js:8 Uncaught ReferenceError: jQuery is not defined(anonymous function) @ bootstrap-datepicker.min.js:8(anonymous function) @ bootstrap-datepicker.min.js:8
index.html:35 Uncaught ReferenceError: $ is not defined
```

**Comment by kineticz** [comment]
Another strange thing. If I try this:

```
    val tf: js.ThisFunction1[dom.Element, Int, ElementDesc] = (e: dom.Element, i: Int) => {
      println("adding index...")
//      return ("index: " + i): ElementDesc
      $("#math"): ElementDesc
    }
    val ulli = $("ul li")
    $("ul li").after("<p>hello</p>")
    println(ulli)
    println(tf)
    ulli.after(tf)
```

I get this:

![](https://www.evernote.com/l/ATGqpSFvHRBClYL8CHExlPjAaNpDZ9FpBUkB/image.png)

**Comment by jducoeur** [comment]
I see -- you're specifying it completely manually, and _not_ loading your jsDependencies.  Which isn't completely chaotic, but is a maintenance challenge.

Not sure it's relevant, but the correct way to do this is to not load any of the JavaScript files manually -- not just jQuery, but also Bootstrap and Bootstrap-Datepicker.  Instead, you want:

```
<script src="target/scala-2.11/sjs-dp-jsdeps.js"></script>
<script src="target/scala-2.11/sjs-dp-fastopt.js"></script>
```

The -jsdeps.js file is what jsDependencies are for -- it is all of the required JavaScript files, concatenated together in the correct order.  -jsdeps.js is generated by the Scala.js compiler automatically, provided that your build.sbt includes

```
skip in packageJSDependencies := false
```

Try that out -- it may not make any difference to this particular problem, but it's more correct.

**Comment by jducoeur** [comment]
As for that latest experiment -- very interesting, and that _is_ what I would expect to see.  `$("#math")` is specifying a particular node in the DOM, so this is trying to move that node to right after each `li`.  It keeps getting moved, and the last one wins.

That's exactly right, I believe.  Still not sure why you're not getting the right behavior from returning a string, though...

**Comment by kineticz** [comment]
Ok. Using that method doesn't make a difference in this case, but still thanks for your correction.

**Comment by kineticz** [comment]
Hm, this does behave correctly:

```
    val tf: js.ThisFunction1[dom.Element, Int, ElementDesc] = (e: dom.Element, i: Int) => {
      println("adding index...")
//      return ("index: " + i): ElementDesc
      $("<p>math</p>"): ElementDesc
    }
```

**Comment by kineticz** [comment]
Could you please run the same project on your machine, just to verify whether the error is reproducible?

**Comment by jducoeur** [comment]
Can't do so easily -- I do all my development remotely, so it's quite a lot of work to add another project.  Sorry.

**Comment by kineticz** [comment]
Ok, no problem.

**Comment by jducoeur** [comment]
Very, very strange.  Returning a JQuery object clearly works correctly for you, but an HTML string doesn't.  I have no idea why that would be...

**Comment by jducoeur** [comment]
Actually, I should check that assumption.  You've tried replacing:

```
("index: " + i): ElementDesc
```

with

```
"<p>hi</p>": ElementDesc
```

or something like that?  That is, HTML rather than just a random string?  (To narrow the difference between the direct-call version and the indirection through the callback.)

**Comment by jducoeur** [comment]
Anyway, I need to head out.  Good luck...

**Comment by kineticz** [comment]
Wow, indeed, this also works:

```
    val tf: js.ThisFunction1[dom.Element, Int, ElementDesc] = (e: dom.Element, i: Int) => {
      println("adding index...")
//      return ("index: " + i): ElementDesc
//      $("<p>math</p>"): ElementDesc
        "<p>math rocks</p>": ElementDesc
    }
```

**Comment by kineticz** [comment]
Suddenly this also works:

```
    val tf: js.ThisFunction1[dom.Element, Int, ElementDesc] = (e: dom.Element, i: Int) => {
      println("adding index...")
      //      return ("index: " + i): ElementDesc
      //      $("<p>math</p>"): ElementDesc
      //        "<p>math rocks</p>": ElementDesc
      "math rocks 1": ElementDesc
    }
```

Very weird. Is this caused by some ghost?

**Comment by jducoeur** [comment]
Well, I'm glad that it's working, although yes, it's a bit mysterious.  I usually find, in cases like this, that there was something subtle -- a typo or such -- that caused one of the intermediate experiments to fail and mislead me about what was going on.

Anyway, I'm going to close out the issue...
